### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Rpsl** [dotzero/git-profile#4]
```
$ git profile add github user.name "Rpsl"                                                                                                       
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/dotzero/git-profile/config.(*Config).Store(...)
	/Users/dotzero/go/src/github.com/dotzero/git-profile/config/config.go:51
github.com/dotzero/git-profile/cmd.NewAdd.func1(0xc0000bc000, 0xc000092780, 0x3, 0x3)
	/Users/dotzero/go/src/github.com/dotzero/git-profile/cmd/add.go:23 +0xf5
github.com/spf13/cobra.(*Command).execute(0xc0000bc000, 0xc000092660, 0x3, 0x3, 0xc0000bc000, 0xc000092660)
	/Users/dotzero/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b42c0, 0xc00007cce0, 0x6, 0x6)
	/Users/dotzero/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/dotzero/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/Users/dotzero/go/src/github.com/dotzero/git-profile/main.go:33 +0x388
```

**Comment by Rpsl** [comment]
Не ясно откуда он берет такой путь, возможно бинарник не идентичен мастеру?

**Comment by dotzero** [comment]
Спасибо за репорт, кажется я понимаю откуда проблема. Исправлю ее как можно скорее.

> Не ясно откуда он берет такой путь, возможно бинарник не идентичен мастеру?
отладочная информация о исходном коде зашита в бинарник

**Comment by dotzero** [comment]
Исправлено в https://github.com/dotzero/git-profile/releases/tag/v1.3.2
